/* eslint-disable */
// Generated by tools/openapi-codegen/generate.mjs. Do not edit by hand.
import { pluginRequest, type PluginApiResponse, type PluginRequestOptions } from '../client-runtime'

export interface Hello {
  message: string
}

export function getHello(options?: PluginRequestOptions): Promise<PluginApiResponse<Hello>> {
  return pluginRequest<Hello>('example.plugin', 'GET', `/hello`, undefined, options)
}
